name: Ping EC2 EsperaZero

on:
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping EC2 Instance
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USERNAME }}
          KEY: ${{ secrets.EC2_KEY }}
        run: |
          chmod 600 deploy_key.pem
          curl -I https://www.google.com
