name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Install SSH Client
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Transfer Files to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "$EC2_KEY" > ec2_key.pem
        chmod 600 ec2_key.pem
        rsync -avz -e "ssh -i ec2_key.pem -o StrictHostKeyChecking=no" ./ $EC2_USERNAME@$EC2_HOST:/home/ec2-user/esperazero/

    - name: SSH into EC2 and Run Deployment Script
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem $EC2_USERNAME@$EC2_HOST << EOF
        cd /home/ec2-user/esperazero
        # Install Node.js dependencies
        npm install
        
        # Build the project
        npm run build
        
        # Install pm2 globally if it's not already installed
        if ! command -v pm2 &> /dev/null
        then
            sudo npm install -g pm2
        fi
        
        # Start or restart the application using pm2
        pm2 restart all || pm2 start npm --name "next-app" -- start

        echo "Deployment complete."
        EOF
