name: Deploy to EC2

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::026090541303:role/GithubEC2AssumeRole
          aws-region: eu-north-1
          audience: sts.amazonaws.com

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Upload Files to S3
        run: |
          aws s3 sync ./ s3://esperazero-build/ --delete

      - name: Run Deployment Commands via SSM
        run: |
          aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=instanceids,Values=${{ secrets.EC2_INSTANCE_ID }}" \
          --parameters 'commands=["aws s3 sync s3://esperazero-build/ /home/ec2-user/esperazero/ --delete", "cd /home/ec2-user/esperazero", "npm install", "npm run build", "if ! command -v pm2 &> /dev/null; then sudo npm install -g pm2; fi", "pm2 restart next-app || pm2 start npm --name next-app -- run start"]' \
          --timeout-seconds 600
