name: Check DNS Resolution

on:
  workflow_dispatch:

jobs:
  test-dns-resolution:
    runs-on: ubuntu-latest
    steps:
    - name: Check DNS for Google
      run: |
        if ! nslookup google.com; then
          echo "DNS resolution failed."
          exit 1
        else
          echo "DNS resolution succeeded."
        fi
      shell: bash
