name: Check Internet Connection

on:
  workflow_dispatch:

jobs:
  test-internet-connection:
    runs-on: ubuntu-latest
    steps:
    - name: Check Internet Connection
      run: |
        if ! curl -s --head --request GET https://www.github.com | grep "200 OK" > /dev/null; then
          echo "Internet connection failed."
          exit 1
        else
          echo "Internet connection is active."
        fi
      shell: bash
